camera_name: usb_cam_1
image_topic: /usb_cam_1/image_raw
has_finish_line: true
merge_zones:
- x_min: 809
  x_max: 950
  y_min: 212
  y_max: 373
fuel_zone:
  x_min: 325
  x_max: 740
  y_min: 217
  y_max: 392
charge_gate_zone:
  x_min: 45
  x_max: 211
  y_min: 534
  y_max: 628
ignore_zones:
- x_min: 781
  x_max: 837
  y_min: 194
  y_max: 234
- x_min: 302
  x_max: 346
  y_min: 331
  y_max: 377
- x_min: 696
  x_max: 745
  y_min: 200
  y_max: 236
finish_line:
  x: 529
  direction: left_to_right
