camera_name: usb_cam_1
image_topic: /usb_cam_1/image_raw
has_finish_line: true
merge_zones:
- x_min: 787
  x_max: 1130
  y_min: 267
  y_max: 475
fuel_zone:
  x_min: 322
  x_max: 793
  y_min: 330
  y_max: 429
charge_gate_zone:
  x_min: 20
  x_max: 340
  y_min: 254
  y_max: 531
ignore_zones:
- x_min: 856
  x_max: 903
  y_min: 308
  y_max: 342
- x_min: 750
  x_max: 794
  y_min: 302
  y_max: 334
- x_min: 334
  x_max: 375
  y_min: 326
  y_max: 361
finish_line:
  x: 879
  direction: left_to_right
