camera_name: usb_cam_1
image_topic: /usb_cam_1/image_raw
has_finish_line: true
merge_zones:
- x_min: 797
  x_max: 1059
  y_min: 362
  y_max: 499
fuel_zone:
  x_min: 340
  x_max: 811
  y_min: 328
  y_max: 427
charge_gate_zone:
  x_min: 52
  x_max: 222
  y_min: 135
  y_max: 497
ignore_zones:
- x_min: 861
  x_max: 913
  y_min: 307
  y_max: 341
- x_min: 764
  x_max: 818
  y_min: 284
  y_max: 327
- x_min: 1188
  x_max: 1253
  y_min: 93
  y_max: 144
finish_line:
  x: 879
  direction: left_to_right
